### ISSUE TITLE
Will continue to collect VS2017, VS2019?

### ISSUE THREAD

**Issue by cryzlasm** [danielplohmann/empty_msvc#1]
version list:

|Ms_VC versison|MSC_VER |
|:-|:-|
|MS VC++14.0|_MSC_VER=1600(VS2015)  |
|MS VC++12.0|_MSC_VER=1600(VS2013)  |
|MS VC++10.0|_MSC_VER=1600(VS2010)  |
|MS VC++9.0|_MSC_VER=1500(VS2008)  |
|MS VC++8.0|_MSC_VER=1400(VS2005)  |
|MS VC++7.0|_MSC_VER=1300  |
|MS VC++7.1|_MSC_VER=1310  |
|MS VC++6.0|_MSC_VER=1200(VC6)|

**Comment by danielplohmann** [comment]
Yes, it's planned to add more versions. 
I just added VS6 and VS2019.
